import AppKit
import Combine
import Foundation
import os

/// Polls `NSPasteboard.general` and maintains bounded history (text and file copies).
///
/// **Concealed items:** any pasteboard change whose types contain `org.nspasteboard.{Concealed,Transient,AutoGenerated}Type`
/// is honored — `changeCount` is advanced so the next non-concealed copy is detected, but the content is not recorded
/// or notified. Password managers and recent macOS releases set these hint types to keep clipboard managers from
/// persisting secrets and one-time codes.
public final class ClipboardHistoryStore: ObservableObject {
    @Published public private(set) var items: [ClipboardItem] = []
    /// Saved independently of history size limits; persisted to `favorites.json`.
    @Published public private(set) var favorites: [ClipboardItem] = []

    /// Preferences (history limits, notifications, etc.).
    public let appSettings: AppSettings
    private var cancellables = Set<AnyCancellable>()
    private var saveWorkItem: DispatchWorkItem?

    private var lastChangeCount: Int
    private var lastFingerprint: String?
    private var pollTimer: Timer?

    private let pollInterval: TimeInterval = 0.35

    private static let log = Logger(subsystem: "ClipboardApp", category: "Persistence")

    /// Hint types that mean "do not record this clipboard item" (passwords, OTPs, transient generated values).
    /// Convention defined at <http://nspasteboard.org/>; honored by macOS Sonoma+ system clipboard and by
    /// password managers like 1Password and Bitwarden.
    private static let concealedHintTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private static var supportDirectoryURL: URL {
        let fm = FileManager.default
        let base = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let dir = base.appendingPathComponent("ClipboardApp", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        // The directory may pre-exist with wider permissions from earlier releases; tighten in-place.
        try? fm.setAttributes([.posixPermissions: 0o700], ofItemAtPath: dir.path)
        return dir
    }

    static var persistenceURL: URL {
        supportDirectoryURL.appendingPathComponent("history.json", isDirectory: false)
    }

    static var favoritesPersistenceURL: URL {
        supportDirectoryURL.appendingPathComponent("favorites.json", isDirectory: false)
    }

    public init(settings: AppSettings) {
        appSettings = settings
        lastChangeCount = NSPasteboard.general.changeCount
        loadFromDisk()
        loadFavoritesFromDisk()

        appSettings.$maxHistoryItems
            .receive(on: DispatchQueue.main)
            .sink { [weak self] max in
                self?.trimToMax(max)
            }
            .store(in: &cancellables)

        appSettings.$encryptClipboardDataAtRest
            .dropFirst()
            .receive(on: DispatchQueue.main)
            .sink { [weak self] _ in
                guard let self else { return }
                saveWorkItem?.cancel()
                saveToDisk()
                saveFavoritesToDisk()
            }
            .store(in: &cancellables)
    }

    public func start() {
        pollTimer?.invalidate()
        pollTimer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            self?.pollPasteboard()
        }
        RunLoop.main.add(pollTimer!, forMode: .common)
        pollPasteboard()
    }

    public func stop() {
        pollTimer?.invalidate()
        pollTimer = nil
        saveWorkItem?.cancel()
        saveToDisk()
        saveFavoritesToDisk()
    }

    private var maxItems: Int {
        AppSettings.clampHistoryCount(appSettings.maxHistoryItems)
    }

    private func trimToMax(_ raw: Int) {
        let m = AppSettings.clampHistoryCount(raw)
        guard items.count > m else { return }
        items = Array(items.prefix(m))
        scheduleSave()
    }

    private func pollPasteboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        // Honor the password-manager / macOS "do not store" convention before reading any content.
        if Self.pasteboardIsConcealed(pb) {
            return
        }

        if let fileURLs = Self.fileURLs(from: pb), !fileURLs.isEmpty {
            let paths = fileURLs.map { $0.standardizedFileURL.path }
            let fp = Self.fingerprintFiles(paths)
            if fp == lastFingerprint { return }
            lastFingerprint = fp
            let content = ClipboardItem.Content.files(paths)
            if matchesFirst(content) { return }
            items.insert(ClipboardItem(content: content), at: 0)
            ClipboardCopyNotifier.notifyIfNeeded(content: content, settings: appSettings)
            trimAndSave()
            return
        }

        guard let text = pb.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !text.isEmpty
        else { return }

        let fp = Self.fingerprintText(text)
        if fp == lastFingerprint { return }
        lastFingerprint = fp

        let content = ClipboardItem.Content.text(text)
        if matchesFirst(content) { return }

        items.insert(ClipboardItem(content: content), at: 0)
        ClipboardCopyNotifier.notifyIfNeeded(content: content, settings: appSettings)
        trimAndSave()
    }

    private static func pasteboardIsConcealed(_ pb: NSPasteboard) -> Bool {
        guard let types = pb.types else { return false }
        return types.contains { concealedHintTypes.contains($0) }
    }

    private func matchesFirst(_ content: ClipboardItem.Content) -> Bool {
        guard let first = items.first else { return false }
        return first.content == content
    }

    private func trimAndSave() {
        let limit = maxItems
        if items.count > limit {
            items.removeLast(items.count - limit)
        }
        scheduleSave()
    }

    private static func fingerprintText(_ s: String) -> String {
        "t:\(s.count)::\(s.hashValue)"
    }

    private static func fingerprintFiles(_ paths: [String]) -> String {
        let sorted = paths.sorted().joined(separator: "\u{1e}")
        return "f:\(sorted.hashValue)::\(sorted.count)"
    }

    private static func fileURLs(from pb: NSPasteboard) -> [URL]? {
        guard let objects = pb.readObjects(forClasses: [NSURL.self], options: nil), !objects.isEmpty else {
            return nil
        }
        var urls: [URL] = []
        for obj in objects {
            let url: URL?
            if let u = obj as? URL {
                url = u
            } else if let ns = obj as? NSURL {
                url = ns as URL
            } else {
                url = nil
            }
            guard let url, url.isFileURL else { continue }
            urls.append(url)
        }
        return urls.isEmpty ? nil : urls
    }

    /// Restores the chosen entry onto the general pasteboard for the next **⌘V** (text or files in Finder-compatible form).
    public func copyContentToPasteboard(_ content: ClipboardItem.Content) {
        let pb = NSPasteboard.general
        switch content {
        case .text(let text):
            pb.clearContents()
            pb.setString(text, forType: .string)
            if let data = text.data(using: .utf8) {
                pb.setData(data, forType: NSPasteboard.PasteboardType("public.utf8-plain-text"))
            }
            lastFingerprint = Self.fingerprintText(text)
            lastChangeCount = pb.changeCount
        case .files(let paths):
            let fm = FileManager.default
            let urls = paths.compactMap { path -> URL? in
                guard fm.fileExists(atPath: path) else { return nil }
                return URL(fileURLWithPath: path)
            }
            guard !urls.isEmpty else { return }
            pb.clearContents()
            pb.writeObjects(urls.map { $0 as NSURL })
            let pathStrings = urls.map(\.path)
            pb.setPropertyList(pathStrings, forType: NSPasteboard.PasteboardType("NSFilenamesPboardType"))
            lastFingerprint = Self.fingerprintFiles(paths)
            lastChangeCount = pb.changeCount
        }
    }

    /// Restores a full history row (same as ``copyContentToPasteboard(_:)`` with `item.content`).
    public func copyItemToPasteboard(_ item: ClipboardItem) {
        copyContentToPasteboard(item.content)
    }

    /// Tells the store that `content` is the pasteboard's current state, so the next ``pollPasteboard`` tick
    /// skips it. Used after `ForegroundSelectionFavoriteCapture` posts a synthetic ⌘C — otherwise the
    /// captured selection would land in history a moment after being added as a favorite.
    public func markPasteboardSynchronized(with content: ClipboardItem.Content) {
        switch content {
        case .text(let s):
            lastFingerprint = Self.fingerprintText(s)
        case .files(let paths):
            lastFingerprint = Self.fingerprintFiles(paths)
        }
        lastChangeCount = NSPasteboard.general.changeCount
    }

    public func isFavorite(id: UUID) -> Bool {
        favorites.contains { $0.id == id }
    }

    /// Reads the general pasteboard as ``ClipboardItem/Content-swift.enum`` (files if present, otherwise trimmed plain text).
    public static func contentFromGeneralPasteboard() -> ClipboardItem.Content? {
        let pb = NSPasteboard.general
        if let fileURLs = fileURLs(from: pb), !fileURLs.isEmpty {
            return .files(fileURLs.map { $0.standardizedFileURL.path })
        }
        guard let text = pb.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !text.isEmpty
        else { return nil }
        return .text(text)
    }

    /// Inserts a new favorite from captured content, or returns an existing favorite with the same content.
    @discardableResult
    public func addFavoriteFromCapturedContent(_ content: ClipboardItem.Content) -> ClipboardItem {
        if let existing = favorites.first(where: { $0.content == content }) {
            return existing
        }
        let item = ClipboardItem(content: content)
        favorites.insert(item, at: 0)
        saveFavoritesToDisk()
        return item
    }

    /// Stars match history rows by id. Tapping again removes from favorites.
    public func toggleFavorite(_ item: ClipboardItem) {
        if let idx = favorites.firstIndex(where: { $0.id == item.id }) {
            favorites.remove(at: idx)
        } else {
            favorites.insert(item, at: 0)
        }
        saveFavoritesToDisk()
    }

    // MARK: - Persistence

    private func loadFromDisk() {
        if let decoded = Self.loadCollection(from: Self.persistenceURL, role: .history) {
            items = Array(decoded.collection.prefix(maxItems))
            if formatMismatch(decoded.envelopeOnDisk) { scheduleSave() }
        }
    }

    private func loadFavoritesFromDisk() {
        if let decoded = Self.loadCollection(from: Self.favoritesPersistenceURL, role: .favorites) {
            favorites = decoded.collection
            if formatMismatch(decoded.envelopeOnDisk) { saveFavoritesToDisk() }
        }
    }

    private struct LoadedCollection {
        let collection: [ClipboardItem]
        let envelopeOnDisk: ClipboardPersistenceCrypto.EnvelopeKind
    }

    private static func loadCollection(
        from url: URL,
        role: ClipboardPersistenceCrypto.Role
    ) -> LoadedCollection? {
        let fm = FileManager.default
        guard fm.fileExists(atPath: url.path) else { return nil }

        let raw: Data
        do {
            raw = try Data(contentsOf: url)
        } catch {
            log.error(
                "Could not read \(url.lastPathComponent, privacy: .public): \(error.localizedDescription, privacy: .public)"
            )
            return nil
        }

        let plaintext: Data
        do {
            plaintext = try ClipboardPersistenceCrypto.unwrap(fileData: raw, role: role)
        } catch let crypto as ClipboardPersistenceCrypto.CryptoError where !crypto.indicatesFileCorruption {
            // Transient Keychain issue — don't touch the file. User can retry after fixing access.
            log.error(
                "Keychain unavailable while loading \(url.lastPathComponent, privacy: .public); skipping load (file left intact)."
            )
            return nil
        } catch {
            log.error(
                "\(url.lastPathComponent, privacy: .public) is unreadable; quarantining. Reason: \(error.localizedDescription, privacy: .public)"
            )
            quarantineUnreadable(at: url)
            return nil
        }

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let decoded: [ClipboardItem]
        do {
            decoded = try decoder.decode([ClipboardItem].self, from: plaintext)
        } catch {
            log.error(
                "\(url.lastPathComponent, privacy: .public) JSON malformed; quarantining. Reason: \(error.localizedDescription, privacy: .public)"
            )
            quarantineUnreadable(at: url)
            return nil
        }

        return LoadedCollection(collection: decoded, envelopeOnDisk: ClipboardPersistenceCrypto.envelopeKind(of: raw))
    }

    /// Renames an unreadable persistence file to `<name>.unreadable-<timestamp>` instead of letting the next
    /// save silently overwrite it. Keeps the original bytes around for forensics / manual recovery.
    private static func quarantineUnreadable(at url: URL) {
        let fm = FileManager.default
        let dir = url.deletingLastPathComponent()
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        let stamp = formatter.string(from: Date()).replacingOccurrences(of: ":", with: "-")
        let target = dir.appendingPathComponent("\(url.lastPathComponent).unreadable-\(stamp)", isDirectory: false)
        do {
            try fm.moveItem(at: url, to: target)
            log.notice("Quarantined \(url.lastPathComponent, privacy: .public) → \(target.lastPathComponent, privacy: .public)")
        } catch {
            log.error(
                "Failed to quarantine \(url.lastPathComponent, privacy: .public): \(error.localizedDescription, privacy: .public)"
            )
        }
    }

    private func scheduleSave() {
        saveWorkItem?.cancel()
        let work = DispatchWorkItem { [weak self] in
            self?.saveToDisk()
        }
        saveWorkItem = work
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.45, execute: work)
    }

    private func saveToDisk() {
        Self.saveCollection(items, to: Self.persistenceURL, role: .history, encrypted: appSettings.encryptClipboardDataAtRest)
    }

    private func saveFavoritesToDisk() {
        Self.saveCollection(favorites, to: Self.favoritesPersistenceURL, role: .favorites, encrypted: appSettings.encryptClipboardDataAtRest)
    }

    private static func saveCollection(
        _ collection: [ClipboardItem],
        to url: URL,
        role: ClipboardPersistenceCrypto.Role,
        encrypted: Bool
    ) {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let json: Data
        do {
            json = try encoder.encode(collection)
        } catch {
            log.error("JSON encode failed for \(url.lastPathComponent, privacy: .public): \(error.localizedDescription, privacy: .public)")
            return
        }

        let bytes: Data
        if encrypted {
            do {
                bytes = try ClipboardPersistenceCrypto.wrap(plaintextJSON: json, role: role)
            } catch {
                // Don't overwrite an existing file with plaintext just because Keychain access failed.
                log.error(
                    "Encryption failed for \(url.lastPathComponent, privacy: .public); skipping write. Reason: \(error.localizedDescription, privacy: .public)"
                )
                return
            }
        } else {
            bytes = json
        }

        do {
            try bytes.write(to: url, options: [.atomic])
        } catch {
            log.error("Write failed for \(url.lastPathComponent, privacy: .public): \(error.localizedDescription, privacy: .public)")
            return
        }

        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }

    /// True when the on-disk envelope does not match the current setting: plaintext under "encrypt = on",
    /// any encrypted envelope under "encrypt = off", or a legacy CLP1 file under "encrypt = on" (re-seal as CLP2).
    private func formatMismatch(_ kind: ClipboardPersistenceCrypto.EnvelopeKind) -> Bool {
        if appSettings.encryptClipboardDataAtRest {
            return kind != .currentV2
        } else {
            return kind != .plain
        }
    }
}
